title: Eduardo Marin – Personal Site
author: Eduardo Marin
email: eduardo.marin117@gmail.com
description: Hi my name is Eduardo. I'm a product designer living and working in New York City.
url: 
twitter_username:
github_username:

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
